---
#
# Ansible managed
#
repository:
  description: Install and configure terraform on your system.
  homepage: https://robertdebock.nl/
  topics: terraform, development, ansible, molecule, playbook
